issue:
  translate:
    replay: |
      此 Issue 的翻譯：
      ---
      ## {title}

      {body}
  needReproduce:
    label: Need Reproduce
    afterLabel: Need More Info
    replay: |
      您好 @{user}，請提供一個線上重現範例，可以透過 fork 此連結 https://stackblitz.com/edit/ng-alain-setup 或提供一個最小化的 GitHub 倉庫。
      標記為 `Need Reproduce` 的 Issue 若 7 天內無回應將會被自動關閉。

      ![](https://gw.alipayobjects.com/zos/antfincdn/y9kwg7DVCd/reproduce.gif)
  invalid:
    mark: ng-alain-issue-helper
    labels: Invalid
    replay: |
      您好 @{user}，為了進行高效溝通，我們對 Issue 有一定的格式要求。您的 Issue 因為不符合要求而被自動關閉。
      請使用 [Issue 助手](https://ng-alain.com/issue-helper/index.html#zh) 來建立 Issue，以方便我們定位問題。謝謝配合！
