# probot-no-response 配置 - https://github.com/probot/no-response

# Issue 因無回應而關閉前的無活動天數
daysUntilClose: 7
# 需要回應的標籤
responseRequiredLabel: Need More Info
# 因無回應而關閉 Issue 時發布的留言。設為 `false` 可停用
closeComment: >
  此 Issue 已被自動關閉，因為原作者未提供更多資訊。目前提供的資訊不足以採取行動。如果您能提供更多資訊，歡迎聯繫維護者重新開啟此 Issue。感謝您的貢獻。

