---
# MCP Servers Configuration
# 參考: .github/agents/context7.agent.md

mcp-servers:
  context7:
    type: http
    url: 'https://mcp.context7.com/mcp'
    headers: { 'CONTEXT7_API_KEY': '${{ secrets.COPILOT_MCP_CONTEXT7 }}' }
    tools: ['get-library-docs', 'resolve-library-id']
